sass:
  sass_dir: ./css/
  style: style.css

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

permalink: pretty
highlighter: pygments